version: '3.4'

services:
  bank_management_microservice:
    image: bank_management_microservice
    restart: on-failure
    ports:
      - "6601:80"
    build:
      context: ./BankManagementMicroservice
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - rabbitmq
  account_information_microservice:
    image: account_information_microservice
    restart: on-failure
    ports:
      - "6602:80"
    build:
      context: ./AccountInformationMicroservice
      dockerfile: Dockerfile
    depends_on:
      - mongodb
      - rabbitmq
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "BankManagementBd"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "1111"
    volumes:
      - ./postgres_scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  mongodb:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - ./mongo_scripts:/docker-entrypoint-initdb.d
  rabbitmq:
    image: rabbitmq:3.10.6-management-alpine
    hostname: my-rabbitmq
    ports:
      - "5672:5672"  
      - "15672:15672"  
volumes:
  mongodb_data: